[[edge_functions]]
function = "index"
path = "/*"

[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "*"

[build]
	command = "echo 'Skipping build (netlify.toml override)'"
